CREATE DATABASE bcnsolutions CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


USE bcnsolutions;


CREATE TABLE subscribers (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) UNIQUE NOT NULL,
ip VARCHAR(45),
country VARCHAR(100),
city VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE pageviews (
id INT AUTO_INCREMENT PRIMARY KEY,
path VARCHAR(255),
ip VARCHAR(45),
country VARCHAR(100),
city VARCHAR(100),
user_agent VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);